### ISSUE TITLE
Voteythumbs occasional error

### ISSUE THREAD

**Issue by lewisjb** [UQComputingSociety/uqcsbot#101]
`TypeError: Cannot read property 'channel' of undefined` (line 63)

**Comment by mitchmcdee** [comment]
140 LOC seems overkill, I think !voteythumbs is due for a refactor so that's it simply listens for `!voteythumbs` and have the bot get the vote started

**Comment by mitchmcdee** [comment]
Voteythumbs was refactored in the pybot swap, so this issue is no longer relevant. Closing
