### ISSUE TITLE
!weather radar not always detected

### ISSUE THREAD

**Issue by lewisjb** [UQComputingSociety/uqcsbot#116]
Due to how weather.js works, sometimes using "!weather radar" will activate the normal "!weather" call.

Suggested fixes:
 - Only have one `robot.respond`
 - Make the RegEx stricter

**Comment by mitchmcdee** [comment]
could you give some examples of what inputs trigger this?

**Comment by lewisjb** [comment]
`!weather radar` & `!weather radar brisbane`, neither run the radar code.

**Comment by gricey432** [comment]
Is this still needed now that we have `!radar`?

**Comment by mitchmcdee** [comment]
I think if we're going to close this ticket and accept having a command for each functionality, we should remove radar code from !weather first :)

**Comment by mitchmcdee** [comment]
Fixed in 33c14a3, closing :)
