### ISSUE TITLE
Welcome message detecting in wrong channel

### ISSUE THREAD

**Issue by gricey432** [UQComputingSociety/uqcsbot#131]
Welcome messages detect in general, which means they get sent again and again if someone leaves general and comes back.
The bot should look for new people in announcements and then post the welcome message in general

**Comment by TRManderson** [comment]
I kind of want to close this as it's useful for debug purposes

**Comment by lewisjb** [comment]
Is it a big enough issue anyway? It's rare for people to leave general. Although, we should change it to count number of people in announcements for the 50 people milestones

**Comment by mitchmcdee** [comment]
Closing as this is a non-issue.

As per Lewis's point to milestones, this was addressed in https://github.com/UQComputingSociety/uqcsbot/pull/166
