### ISSUE TITLE
Welcome script use display names

### ISSUE THREAD

**Issue by lewisjb** [UQComputingSociety/uqcsbot#161]
With the change of display names, the welcome script uses a weird name now. Easiest solution might just be to ping them.

**Comment by mitchmcdee** [comment]
Addressed in https://github.com/UQComputingSociety/uqcsbot/pull/166, will close once merged :)

**Comment by mitchmcdee** [comment]
Fixed in 421bcc4a631f2dce0e2bccb58a8a24b14558085c, closing

**Comment by CameronAavik** [comment]
As we have seen, `display_name` is optional, so we should default to `name` if it is empty

**Comment by mitchmcdee** [comment]
As @lewisjb was saying on slack, do we want display_name or display_name_normalised? (if display_name is old/going to be deprecated?)

**Comment by mitchmcdee** [comment]
again as per slack discussion, it was decided `display_name` is fine for our use

**Comment by mitchmcdee** [comment]
Fixed in 03fcd9a9d2ea80d5c2b74bca7669b020438f6442, closing
