### ISSUE TITLE
Welcome message needs updating

### ISSUE THREAD

**Issue by mitchmcdee** [UQComputingSociety/uqcsbot#167]
Currently is:

`Hey there! Welcome to the UQCS slack!`
`This is the first time I've seen you, so you're probably new here`
`I'm UQCSbot, your friendly (open source) robot helper`
`We've got a bunch of generic channels (e.g. #banter, #games, #projects) along with many subject-specific ones`
`Your friendly admins are @trm, @mitch, @rob, @mb, @csa, @guthers, and @artemis`
`Type "help" here, or "!help" anywhere else to find out what I can do!`
`and again, welcome :)`

I think it needs a lil refresh, including being:

- More friendly and welcoming
- Showcase more of UQCSbot features
- Introduce the exec team a little better
- Talk about the community a little more and encourage them to introduce themselves on general
- Guide them to finding channels (I know slack does this, but still)

Thoughts are appreciated :)

**Comment by TRManderson** [comment]
All v. great ideas!

**Comment by rob** [comment]
Looks great!

**Comment by TRManderson** [comment]
Sorry about the tags for people with GitHub usernames that happen to be the Slack usernames of our admins 😆

**Comment by mitchmcdee** [comment]
Bahahahahahha what a goof didn't know it would tag

**Comment by mb** [comment]
What is this and why i'm in here

**Comment by MaxwellBo** [comment]
I think they were trying to tag me @mb

**Comment by mitchmcdee** [comment]
![image](https://user-images.githubusercontent.com/10495244/43366151-3773e80e-937c-11e8-8d41-5217436857a1.png)
