### ISSUE TITLE
Feature Request: Add a command to provide helpful links for mental health

### ISSUE THREAD

**Issue by coppers-j** [UQComputingSociety/uqcsbot#175]
Add a command for quick access to vital links for times of need, don't have the time to do it myself but think would be a helpful feature.

**Example Message:**
For assistance with understanding your problems and identifying self-help strategies, UQ Student Services can be found at http://www.uq.edu.au/student-services/counselling-services. For immediate help, Lifeline provides an online support chat at https://www.lifeline.org.au/Get-Help/Online-Services/crisis-chat from 7pm until midnight every night, as well as a 24/7 hotline on `13 11 14`.
In Emergencies Call UQ Security on `07 3365 3333`

**Comment by wisebaldone** [comment]
This could also contain information about Student Disability Action Plans so that UQ can become aware and put things in place.

**Comment by mitchmcdee** [comment]
I personally don't see the difference between the intent behind googling for help vs typing in the command, what does it offer differently?

I think having some message (like the one you've provided) pinned in a help channel would serve this same purpose a lot more effectively. I also liked your idea that you said on slack (I think) about a cronjob that posts a message like that every x hours/day

**Comment by coppers-j** [comment]
The idea behind the command is if someone is in need of help another person on slack could type the command and quickly get links for them, but yeah I think periodically posting the message on a specified channel would be just as good.

**Comment by bradleysigma** [comment]
I guess this is closed with #435.
