### ISSUE TITLE
Bug: messages containing the word "latex" trigger the latex command incorrectly 

### ISSUE THREAD

**Issue by CameronAavik** [UQComputingSociety/uqcsbot#181]
It seems to only trigger if there are words surrounding "latex"

**Comment by CameronAavik** [comment]
Looks like the issue is the [regex](https://github.com/UQComputingSociety/uqcsbot/blob/master/scripts/latex.js#L10)

    /\$\$([^\$]+)\$\$ | !?(tex|latex) ([^\$]+)/

It should be

    /\$\$([^\$]+)\$\$|!(tex|latex) ([^\$]+)/

**Comment by mitchmcdee** [comment]
Fixed in 1d90a3d, closing
