### ISSUE TITLE
Member milestones still seems to be broken

### ISSUE THREAD

**Issue by mitchmcdee** [UQComputingSociety/uqcsbot#191]
More logging is necessary to see what exactly is going on >:(

**Comment by CameronAavik** [comment]
I think it's because you are using `==` instead of `===` here
https://github.com/UQComputingSociety/uqcsbot/blob/master/scripts/welcome.js#L19

in javascript, `0 == ""`

**Comment by CameronAavik** [comment]
Wait, never mind, cursor is the 4th argument, not the third. my bad :joy:

**Comment by mitchmcdee** [comment]
Regardless, that same code is working for `wakie.js`, so I'm wondering what is going on :\

**Comment by TRManderson** [comment]
Still a thing?

**Comment by mitchmcdee** [comment]
Keeping open until I know for sure it works lol. We'll see in 13 members

**Comment by mitchmcdee** [comment]
Will close if #319 is successful for 1600 users.

**Comment by mitchmcdee** [comment]
Closing as this is now fixed :^)
