### ISSUE TITLE
Feature Request: !attic <COURSE_CODE>

### ISSUE THREAD

**Issue by mitchmcdee** [UQComputingSociety/uqcsbot#208]
returns all the files found in the course's uqattic drive folder

**Comment by tgrkzus** [comment]
Could `!attic` alone just link the root directory of the drive?

**Comment by mitchmcdee** [comment]
sure it could, but where's the fun in that? ;)

**Comment by mitchmcdee** [comment]
oh I see, you're saying for an empty option-- that's a good idea :^)

**Comment by mitchmcdee** [comment]
I actually did this in #217, but needs to be ported to python in #259. Will close for now as that issue will track completion.
