### ISSUE TITLE
Race condition in !urban

### ISSUE THREAD

**Issue by mitchmcdee** [UQComputingSociety/uqcsbot#209]
need to make sure the first message is sent before we send the second
@nickl93 :^)

**Comment by nickl93** [comment]
plz close :^)

**Comment by mitchmcdee** [comment]
Will close once #211 is pushed :^)

**Comment by mitchmcdee** [comment]
Fixed in 3227dce958aa1eaf1ac2bdb83f83efca8422a0ed, closing
