### ISSUE TITLE
Feature Request/Improvement: Add 'usage:' to all scripts that don't already have it

### ISSUE THREAD

**Issue by mitchmcdee** [UQComputingSociety/uqcsbot#214]
Support incorrect usages in regex and give feedback back to user

**Comment by nickl93** [comment]
I'm taking care of this, also fixing the regex re: trailing characters (e.g. !catch calling !cat).

**Comment by mitchmcdee** [comment]
Closing this as `!help` should take care of it. Also, the move to pybot removed regexs

**Comment by mitchmcdee** [comment]
On second thought, I think it might be necessary. I like @MaxwellBo's idea in #312 to just print back the doc, we should use that elsewhere

**Comment by mitchmcdee** [comment]
Can probably add it to `on_command` and add a `UsageSyntaxException` to automate it :^)
