### ISSUE TITLE
!radar shows radar on client render, not when called

### ISSUE THREAD

**Issue by gricey432** [UQComputingSociety/uqcsbot#218]
If someone does `!radar` at 12:00 and I open slack at 14:00, I'll see the radar for 14:00. This leads to situations where if you don't open the radar channel for a while, it will look like every radar is the same.

This can't really be fixed in slack itself though. What I might do is improve the BOM proxy API so it scrapes half-hourly and then when you call the api it'll load from the cache for the given timestamp.

Or we could fix this in slack by changing UQCS bot to download the image from bomproxy and upload the image itself to slack. This seems like a waste of space though

**Comment by mitchmcdee** [comment]
I believe this has been fixed in #383 , closing
