### ISSUE TITLE
Wakie returns uqcsbot twice instead of random members

### ISSUE THREAD

**Issue by CameronAavik** [UQComputingSociety/uqcsbot#220]
![image](https://user-images.githubusercontent.com/5800980/35084774-42aba2ea-fc71-11e7-9a0e-1f785e702196.png)

The bot seemed to tag a new user twice a few days ago as well, not sure why but this has only occurred once
![image](https://user-images.githubusercontent.com/5800980/35084807-6ec9b858-fc71-11e7-833f-68379c350ef2.png)

Issue is probably somewhere in [wakie.js](https://github.com/UQComputingSociety/uqcsbot/blob/master/scripts/wakie.js)

Maybe [conversations.members](https://api.slack.com/methods/conversations.members) has changed?

**Comment by mitchmcdee** [comment]
Closing as the move to pybot as inherently fixed this bug.
