### ISSUE TITLE
Porting over commands to the python rewrite

### ISSUE THREAD

**Issue by CameronAavik** [UQComputingSociety/uqcsbot#237]
This is an issue to track the porting of commands to python.

Github is currently pointing to the python-rewrite branch, however the master branch in javascript is what is currently deployed to the bot.

There are a number of commands that are pending to be ported over which can be found in the `unimplemented_commands` directory ([Link](https://github.com/UQComputingSociety/uqcsbot/tree/python-rewrite/unimplemented_commands)).

I don't think we need to merge over every single command for us to switch over, as I would like to have it switched over sooner rather than later. We should choose which commands should be implemented for us to accept it as ready.

I propose that the following commands should be ported before switching over:
- [x] !ecp
- [x] !events
- [x] !help
- [x] !pastexams
- [x] !radar
- [x] !repo
- [x] !voteythumbs
- [x] wakie
- [x] wavie
- [x] welcome
- [x] !whatsdue

If you would like to assist with the rewrite, please choose any of the commands above (although feel free to port over other commands as well)

**Comment by CameronAavik** [comment]
One of the hackathon projects from last year was a python rewrite of uqcsbot. A number of the above commands were ported over there, so we could copy some of them over.

https://github.com/tgrkzus/uqcsbot/tree/master/uqcsbot/plugins

**Comment by ashfordneil** [comment]
Happy to give !whatsdue a go

**Comment by CameronAavik** [comment]
I'm taking on !events

**Comment by CameronAavik** [comment]
I'm taking on !vote next

**Comment by mitchmcdee** [comment]
Added `!help` in #273

**Comment by mitchmcdee** [comment]
Adding `!whatsdue` in #287

**Comment by mitchmcdee** [comment]
Closing as all the checkpoint items have been completed :)
