### ISSUE TITLE
Handle Rate Limiting of Slack API

### ISSUE THREAD

**Issue by CameronAavik** [UQComputingSociety/uqcsbot#249]
It seems that the issues we are having are caused by rate limiting in the Slack Web API: https://api.slack.com/docs/rate-limits

The reason we only see this on our actual slack and not the test slack is because there are so many members that it paginates the results when looping through the channel members, and we are not rate limiting our pagination attempts.

We apparently need to listen for a HTTP 429 Too Many Requests response and that will tell us how long to wait (in seconds!) until we should try again.

**Comment by CameronAavik** [comment]
Also of note is the Limits section of https://api.slack.com/rtm

>The message server will disconnect any client that sends a message longer than 16 kilobytes. This includes all parts of the message, including JSON syntax, not just the message text. Clients should limit messages sent to channels to 4000 characters, which will always be under 16k bytes even with a message comprised solely of non-BMP Unicode characters at 4 bytes each. If the message is longer a client should prompt to split the message into multiple messages, create a snippet or create a post.
>
>As with all Slack APIs, the RTM API is subject to rate limits. Clients should not send more than one message per second sustained. If you do you may receive an error message or be disconnected.

This seems to indicate that we should have a second between every API message :/

**Comment by mitchmcdee** [comment]
is this a pybot limitation? as far as I remember, we should only be doing like 2 API calls-- which doesn't sound like it should be rate limited

**Comment by CameronAavik** [comment]
This is a pybot limitation, because it actually does pagination, the jsbot doesn't do pagination which causes it to not get all the members in the channel for wakie.

**Comment by mitchmcdee** [comment]
I wrote the pagination code for JS-- but maybe the reason it didn't work was the same reason here, it was being rate limited

**Comment by mitchmcdee** [comment]
although tbh I would have expected our JS backend to handle rate limiting

**Comment by CameronAavik** [comment]
Where did we do pagination? the code was just using hubot which didn't do pagination.

**Comment by CameronAavik** [comment]
Anyhow, because of how it is a shared rate limit, we should implement a queue for processing these messages which can centrally handle the rate limiting, it's going to be quite messy though to implement and we should design a proper solution first.

@TRManderson any immediate thoughts?

**Comment by mitchmcdee** [comment]
Ahhhh yes I remember now. I orignally wrote the pagination then we reverted to just using the slack datastore

**Comment by mitchmcdee** [comment]
short design write-up sgtm

**Comment by CameronAavik** [comment]
Rate limiting is still an open issue on `python-slackclient` https://github.com/slackapi/python-slackclient/issues/287

However, it has been implemented in their nodejs sdk in December last year. You can check out the source here: https://github.com/slackapi/node-slack-sdk/blob/master/lib/clients/client.js

The way they have done it is by creating a `requestQueue` and a wrapper for all API requests called `_makeAPICall` which pushes to that queue, and returns a promise for when it has been processed on that queue. It then sends this, and handles the response in this function: https://github.com/slackapi/node-slack-sdk/blob/master/lib/clients/transports/call-transport.js#L134

If it gets a rate limit response it pauses the queue, waits the specified timeout period, tries again, and then resumes the queue.

So, if we upgraded jsbot to the latest version of the slack-hubot api then it would actually be using pagination it seems.

As you can see, this gets very complex very quickly :/

**Comment by TRManderson** [comment]
We can chuck rate limiting in APIWrapper without too much difficulty I reckon, just gotta incur some per-request overhead in creating synchronisation primitives

**Comment by CameronAavik** [comment]
Seems as well there is some example code here for handling rate limiting
https://github.com/slackapi/python-slackclient/blob/master/docs-src/basic_usage.rst#web-api-rate-limits

**Comment by CameronAavik** [comment]
Here is a discussion that I found in a slack dev bot slack which explains some things not in the docs
![image](https://user-images.githubusercontent.com/5800980/36929721-ba978a1c-1ee0-11e8-8914-4ddfa7830990.png)
