### ISSUE TITLE
Python bot doesn't respond to commands via PM

### ISSUE THREAD

**Issue by CameronAavik** [UQComputingSociety/uqcsbot#251]
Haven't had the chance to investigate this further, but from some discussion in #bot-testing we found that when PMing the bot, the ChannelWrapper returns `None` and this is being used in `Command.from_message` https://github.com/UQComputingSociety/uqcsbot/blob/dd4218df42b6af623761f087dafe74873437996e/uqcsbot/base.py#L34

**Comment by mitchmcdee** [comment]
Fixed in 939c1ebdc5bfb2d2a76ccebe1995c1ecc4d3f62a
