### ISSUE TITLE
Add testing framework

### ISSUE THREAD

**Issue by gricey432** [UQComputingSociety/uqcsbot#254]
Each command should provide automated tests to allow commands to be tested without a slack workspace

**Comment by mitchmcdee** [comment]
yyyyyyESSsss we very much need tests bahahahaha

**Comment by gricey432** [comment]
Framework is in. Now we need more tests

**Comment by mitchmcdee** [comment]
Added a work in progress version with async support in #277

**Comment by mitchmcdee** [comment]
Will close this issue once #292 is complete (and subsequently will remove #277)

**Comment by mitchmcdee** [comment]
Adding of tests has been moved to #294

**Comment by mitchmcdee** [comment]
as the sync version is complete, and as the process of porting the useful sections of #277 has been moved to #296, I'll close this issue now :^)
