### ISSUE TITLE
Feature: Add a daily "what weird day is it" announcement

### ISSUE THREAD

**Issue by gricey432** [UQComputingSociety/uqcsbot#275]
At midnight or so the bot would say what celebratory day it is.
e.g for today it would say something like
`Today is National Lima Bean Respect Day`

**Comment by mitchmcdee** [comment]
https://www.timeanddate.com/holidays/fun/
good list I found

**Comment by adriant4456** [comment]
Is someone working on this?

**Comment by gricey432** [comment]
Nice one @ldgrp
