### ISSUE TITLE
Enforce async?

### ISSUE THREAD

**Issue by mitchmcdee** [UQComputingSociety/uqcsbot#282]
Could we save a lot of code complexity if we just enforce all commands to be async functions? Are there any downsides to this?

**Comment by TRManderson** [comment]
Async scripts have a decent chunk of complexity in them. Not sure it's the most beginner friendly.

**Comment by mitchmcdee** [comment]
We don't have to enforce async implementation perse, just use `async def` is more what I mean

**Comment by TRManderson** [comment]
If you use `async def` but don't have an async impl, it clogs up the whole bot waiting for your requests to finish.

**Comment by mitchmcdee** [comment]
wat

**Comment by TRManderson** [comment]
See #285 for what's required for asyncio to actually be a benefit rather than a hindrance

**Comment by mitchmcdee** [comment]
Moving this comment over from #285:

```[I'm] a bit concerned about the complexity and readability sacrifices we're making in exchange for async; ideally that's why I was asking whether it was feasible to enforce async (#282) for everything so that we can abstract things such as with as_async as well as simplify the core code base```

No need to respond, just having it documented. just something we should think about/discuss at some point :^)
