### ISSUE TITLE
Reminding the bot

### ISSUE THREAD

**Issue by lewisjb** [UQComputingSociety/uqcsbot#30]
Idea:
Use `/remind @uqcsbot end vote 6pm` for example (or `!remind end vote 6pm`) and at 6pm uqcsbot will run `end vote`

Slack has `/remind` built in, but you can't target bots

So either:
Remove that restriction for uqcsbot, or add `!remind`

The main problem is getting uqcsbot to run a different command (in this case `end vote`), solving this issue will also solve #25

**Comment by lewisjb** [comment]
http://stackoverflow.com/questions/18139733/calling-one-command-from-another
&
hubot-cronjob

**Comment by lewisjb** [comment]
Regex: /([0-9]{1,2})(:[0-9]{1,2})?(am|pm)?/i

Matches:
*1. Hours
2. ":<minutes>"
3. "am" or "pm"

*Required

**Comment by lewisjb** [comment]
`robot.listeners` will help

example:
```
listeners:
   [ TextListener {
       robot: [Circular],
       regex: /^\s*[@]?(?:uqcsbot[:,]?|![:,]?)\s*(?:!?acro (.+))/i,
       options: [Object],
       callback: [Function],
       matcher: [Function] },
     TextListener {
       robot: [Circular],
       regex: /^\s*[@]?(?:uqcsbot[:,]?|![:,]?)\s*(?:!?caesar(\d*) (.+))/i,
       options: [Object],
       callback: [Function],
       matcher: [Function] },
```

**Comment by mitchmcdee** [comment]
Closing due to lack of interest (and I think application), happy to reopen if people want though :)
