### ISSUE TITLE
Tests are not run on Jenkins

### ISSUE THREAD

**Issue by TRManderson** [UQComputingSociety/uqcsbot#305]
Backend issue, mainly a reminder for me to fix this. Very simple to do, just need to add some stuff to the Jenkins script and run it until the output is good. May as well add coverage too.

**Comment by mitchmcdee** [comment]
It'd be great if we could have jenkins build + run tests for PRs as well

**Comment by TRManderson** [comment]
Test are now run on Jenkins with test and coverage reports published. (coverage only published on successful builds)
