### ISSUE TITLE
Enforce a line limit

### ISSUE THREAD

**Issue by TRManderson** [UQComputingSociety/uqcsbot#327]
We're looking at adding linting, and it turns out to be really easy if we use `tox` (PR incoming)

The `tox` change makes it so that all our tests with coverage calculations are done just by running `tox`. It also means that adding linting doesn't change the workflow for running tests beyond this.

`flake8` seems to be the recommended linter currently - to support typing we need to suppress unused import errors. I think the best option here is to make them not count as a test failure but still report the violations, as unused import errors are still valuable.

It also means we need to agree on a line limit

**Comment by TRManderson** [comment]
Mitch and I reckon 100 is probs fine line limit wise btw, anyone prefer something else strongly?

**Comment by mitchmcdee** [comment]
Close since its added or do you want input?

**Comment by TRManderson** [comment]
Renamed the issue to reflect the fact we now have linting

**Comment by mitchmcdee** [comment]
Closing since we're now enforcing linting + line limits, so I don't really see the point of this issue (feel free to reopen if you're looking for further discussion; but pls specify what)
