### ISSUE TITLE
Outdated 'help' (and fixing for alias)

### ISSUE THREAD

**Issue by lewisjb** [UQComputingSociety/uqcsbot#34]
`uqfinal` and `new reaction` have outdated documentation:
uqcsbot <uqfinal|wdinotf|final> <course> <score1> <score2> ... - (scores are the percentages) Returns the minimum mark on the final exam to pass (doesn't include hurdles)
uqcsbot new reaction <reaction_string> <url to reaction image>

This is inconsistent with the others as it mentions uqcsbot.

The other issue is the commands that use the alias for command usage:
! end vote

There is a space (which is valid, but inconsistent).

And finally:
! go down - Shuts down !, waiting to get restarted

The alias (!) shouldn't be used for `Shuts down !`

**Comment by svict4** [comment]
Nope, still messed for some scripts

**Comment by mitchmcdee** [comment]
Cleaned up help in 379e900b1913f3c18934b561ad51c4fb3d9828f9. Closing
