### ISSUE TITLE
Add ASCI text generator

### ISSUE THREAD

**Issue by Guthers** [UQComputingSociety/uqcsbot#343]
Can use the following API to generate for us
BaseURL = http://artii.herokuapp.com/
Get text "foobar". Request to BaseURL += "make?text=foobar"
Get list of avaliable fonts. Request to BaseURL += "fonts_list"
Get text "foobar" with font "larry3d". Request to BaseURL + "make?text=foobar&font=larry3d"
Using this stuff should make this process pretty simple

**Comment by adriant4456** [comment]
I'll work on this one :)

**Comment by mitchmcdee** [comment]
noice :^)
