### ISSUE TITLE
Add #jobs-bulletin listener.

### ISSUE THREAD

**Issue by nicklambourne** [UQComputingSociety/uqcsbot#344]
As suggested in the #uqcs-meta channel, set up a listener for posts to #jobs-bulletin that posts a follow up message there directing all questions/related discussion to #jobs-discussion. 

Message should be a generic notice that the channel is for job postings only so as to not be out of place should the poster decide upon seeing it to remove their message. 

Additionally, a message should be sent to poster explaining the purpose of the bulletin (and outlining any rules/suggestions for posts there - i.e. fair work compliance, and a warning about what to expect on posting an 'unpaid role').

**Comment by mitchmcdee** [comment]
I think the first two paragraphs should be the focus of a bot feature and the final paragraph probably implemented instead as a "READ ME BEFORE POSTING" on the channel (i.e. in description or some shit)
