### ISSUE TITLE
Add ability to !mock custom text

### ISSUE THREAD

**Issue by mitchmcdee** [UQComputingSociety/uqcsbot#361]
e.g. `!mock something` -> `sOMeThinG`

**Comment by LaVieEstDure** [comment]
Yes please

**Comment by notmitchmcdee** [comment]
Kkkkkkk

**Comment by mitchmcdee** [comment]
I accidentally wiped this when I was showing how I "couldn't force push"
need to do another PR :(
https://github.com/notmitchmcdee/uqcsbot/tree/mock_additions

**Comment by mitchmcdee** [comment]
Fixed in #374
