### ISSUE TITLE
Fix !whatsdue for semester 2

### ISSUE THREAD

**Issue by JamesDearlove** [UQComputingSociety/uqcsbot#369]
When using !whatsdue, if a course was available in semester 1, it will display semester 1 assessment info rather than semester 2 info

**Comment by ldgrp** [comment]
Appending "&offer=53544c554332494e" to the Course Profile URL highlights the current course offering. I'd submit a pull request but it's too much of a hacky fix and requires the URL to be changed every semester.

**Comment by KentonLam** [comment]
It looks like that hex code is an encoded string. For example,
```python
>>> import binascii
>>> binascii.hexlify(b'STLUC2IN')
b'53544c554332494e'
>>> binascii.unhexlify(b'53544c554332494e')
b'STLUC2IN'
```
We probably could get the current date then generate the correct offer code.

**Comment by mitchmcdee** [comment]
oooo nice find!

**Comment by cjfloresalonso** [comment]
Would you have to specify the year then?
