### ISSUE TITLE
Make issues for useful unimplemented_commands we want to port, cull the rest

### ISSUE THREAD

**Issue by mitchmcdee** [UQComputingSociety/uqcsbot#371]
As per title. Realistically I want to get rid of https://github.com/notmitchmcdee/uqcsbot/tree/master/unimplemented_commands, so we need to determine what is useful to port (which we should make an issue to track) and what can be culled.

**Comment by bradleysigma** [comment]
Remaining `unimplemented_commands` split into issues #459, #460, #461, #462, #463, #464, #465, #466, #467, #468 & #469.
