### ISSUE TITLE
!define [word]

### ISSUE THREAD

**Issue by Guthers** [UQComputingSociety/uqcsbot#393]
Add a command to get a definition of a word.

Format of command something like 
`!define [word]`

Obviously connecting up to some sort of API. 
https://developer.oxforddictionaries.com/

Could later have a -oxford -other_dictionary

**Comment by TRManderson** [comment]
https://github.com/UQComputingSociety/uqcsbot/blob/master/uqcsbot/scripts/define.py

**Comment by Guthers** [comment]
I'm a fucking idiot
