### ISSUE TITLE
Better Holidays

### ISSUE THREAD

**Issue by nicklambourne** [UQComputingSociety/uqcsbot#411]
Add more relevant holidays to !holiday: 

- https://www.engadget.com/2016/01/01/the-complete-guide-to-geek-holidays/

These would need to be translated into a better format, but happy to stick a csv on the server or put a new table in the postgres DB to facilitate this.

I'd suggest using the geek holidays and reverting to the others if there are none on that day.

**Comment by LauchieHarvey** [comment]
I scraped a website to compile a .csv. This is my first code contribution so bear with me :). Where in the directory structure should the .csv go? @nicklambourne

**Comment by LauchieHarvey** [comment]
#535

**Comment by nicklambourne** [comment]
Please make a new directory to put it in at `uqcsbot/uqcsbot/static`.
