### ISSUE TITLE
!voteythimbs

### ISSUE THREAD

**Issue by kumar-ish** [UQComputingSociety/uqcsbot#518]
Add a command `!voteythimbs` so that the committee/others can have voting on non-urgent issues but without alerting them with pings. I would very much understand if this was closed to no avail, but it would make things easier (albeit more bloated).

**Comment by John123Allison** [comment]
Hi, can you give more detail on what you're looking for? I.e. should it just alert with a message or does it need to implement a slack feature?

I would like to work on this. Thanks!

**Comment by nicklambourne** [comment]
He wants it to replicate the !voteythumbs behaviour that already exists, but with a different keyword. This can be accomplished by adding the decorator @bot.on_command('voteythimbs') above the existing decorator in [uqcsbot/uqcsbot/scripts/voteythumbs.py](https://github.com/UQComputingSociety/uqcsbot/blob/master/uqcsbot/scripts/voteythumbs.py).
