### ISSUE TITLE
!google not working

### ISSUE THREAD

**Issue by lewisjb** [UQComputingSociety/uqcsbot#59]
title

**Comment by TRManderson** [comment]
{"responseData": null, "responseDetails": "The Google Web Search API is no longer available. Please migrate to the Google Custom Search API (https://developers.google.com/custom-search/)", "responseStatus": 403}

**Comment by mitchmcdee** [comment]
Removed !google in latest commit-- should be trivial to re-add though if someone wanted to do it (which I think is low priority because I hadn't ever seen anyone try using it)
