### ISSUE TITLE
uqcsfood

### ISSUE THREAD

**Issue by lewisjb** [UQComputingSociety/uqcsbot#93]
Get hubot to post all pictures tagged #uqcsfood

@TRManderson happy birthday!

**Comment by TRManderson** [comment]
@lewisjb

**Comment by JosephGarrone** [comment]
Voting to close

**Comment by JosephGarrone** [comment]
@TRManderson  this is not the place for these messages

**Comment by mitchmcdee** [comment]
due to lack of interest (both here and on https://www.instagram.com/explore/tags/uqcsfood/) I'll close this, happy to reopen if its something people want though :)
